import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { DM_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import ProviderApollo from "@/components/providers/ApolloProvider";
import ClientProvider from "@/components/providers/ReactQueryProvider";
import { ContextProvider } from "@/context";
import { Toaster } from "@/components/ui/toaster";

const font = DM_Sans({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Memory Vault",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  

  return (
    <ClerkProvider
      appearance={{ baseTheme: dark }}
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en" suppressHydrationWarning>
        <body className={font.className}>
          <ProviderApollo>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <ClientProvider>
                <ContextProvider>{children}
                <Toaster />
                </ContextProvider>
              </ClientProvider>
            </ThemeProvider>
          </ProviderApollo>
        </body>
      </html>
    </ClerkProvider>
  );
}
